SET IDENTITY_INSERT [dbo].[Foods] ON
INSERT INTO [dbo].[Foods] ([Id], [Name], [Quantity], [Price], [Expire]) VALUES (2, N'Bread', 5, 600, N'2021-03-23 00:00:00')
INSERT INTO [dbo].[Foods] ([Id], [Name], [Quantity], [Price], [Expire]) VALUES (5, N'Biscuits', 5, 110, N'2021-06-25 00:00:00')
INSERT INTO [dbo].[Foods] ([Id], [Name], [Quantity], [Price], [Expire]) VALUES (6, N'Eggs', 200, 15, N'2021-03-10 00:00:00')
INSERT INTO [dbo].[Foods] ([Id], [Name], [Quantity], [Price], [Expire]) VALUES (7, N'Rice', 10, 500, N'2022-01-20 00:00:00')
INSERT INTO [dbo].[Foods] ([Id], [Name], [Quantity], [Price], [Expire]) VALUES (8, N'biki', 66, 888, N'2021-02-22 00:00:00')
SET IDENTITY_INSERT [dbo].[Foods] OFF
